[2024-02-05T06:46:52.197+0000] {taskinstance.py:1097} INFO - Dependencies not met for <TaskInstance: retrain_dag.train_and_save_model scheduled__2024-02-04T14:40:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-02-05T06:46:52.224+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
