[2023-12-27T15:53:00.394+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T15:52:00+00:00 [queued]>
[2023-12-27T15:53:00.401+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T15:52:00+00:00 [queued]>
[2023-12-27T15:53:00.401+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-27T15:53:00.413+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): consume_task> on 2023-12-27 15:52:00+00:00
[2023-12-27T15:53:00.416+0000] {standard_task_runner.py:57} INFO - Started process 360 to run task
[2023-12-27T15:53:00.418+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'consumer_dag', 'consume_task', 'scheduled__2023-12-27T15:52:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/consumer.py', '--cfg-path', '/tmp/tmpebt1pfhy']
[2023-12-27T15:53:00.419+0000] {standard_task_runner.py:85} INFO - Job 357: Subtask consume_task
[2023-12-27T15:53:00.453+0000] {task_command.py:410} INFO - Running <TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T15:52:00+00:00 [running]> on host c56b1de7f6cf
[2023-12-27T15:53:00.511+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consumer_dag' AIRFLOW_CTX_TASK_ID='consume_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-27T15:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-27T15:52:00+00:00'
[2023-12-27T15:53:20.513+0000] {logging_mixin.py:150} INFO - 메시지 없음
[2023-12-27T15:53:20.517+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-12-27T15:53:20.525+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=consumer_dag, task_id=consume_task, execution_date=20231227T155200, start_date=20231227T155300, end_date=20231227T155320
[2023-12-27T15:53:20.543+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-12-27T15:53:20.557+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
